---
# tasks file for ansible-role-postgresql

- name: increase shared memory allocation size
  sysctl: name=kern.sysv.shmall value=131072000 state=present

- name: increase shared memory max
  sysctl: name=kern.sysv.shmmax value=524288000 state=present

- name: install postgresql
  homebrew: name=postgresql state=latest

- name: blow away default image's data directory
  file: path=/usr/local/var/postgres state=absent

- name: create the database
  shell: /usr/local/bin/initdb -U postgres --encoding=utf8 --locale=en_US /usr/local/var/postgres

- name: install launchagents
  file: src=/usr/local/opt/postgresql/homebrew.mxcl.percona-server.plist path=~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist state=link force=yes

- name: check if postgresql is loaded
  shell: launchctl list
  changed_when: False
  register: postgresql_loaded_result

- name: launch mysql
  shell: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
  when: "'homebrew.mxcl.postgresql' not in postgresql_loaded_result.stdout"

- pause: seconds=5
